image: maven:3-eclipse-temurin-21-alpine

variables:
  TP_DIR: "temp"

deploy:
  only:
    - main
  before_script:
    - chmod +x ci/setup-mvn-proxy.sh
    - ./ci/setup-mvn-proxy.sh
    - chmod 400 $CI_SSH_KEY
    - apk add openssh-client
  script:
    - cd $TP_DIR
    - mvn clean package
    - scp -i $CI_SSH_KEY -o StrictHostKeyChecking=no target/*.war gitlabci@192.168.75.18:/opt/tomcat/webapps/c02_tracker.war
