image: node:23-alpine

stages:
  - setup
  - deploy

variables:
  DEPLOY_PATH: '/var/www/'
  DEPLOY_USER: 'gitlabci'
  HOST: '192.168.75.18'

before_script:
  - chmod 400 $CI_SSH_KEY

setup_environment:
  stage: setup
  script:
    - apk add --no-cache openssh

deploy_and_run_api:
  stage: deploy
  only:
    - main
  script:
    - cd ./api
    - npm install
    - node ace build
    - mv build api-app
    - scp -r -o StrictHostKeyChecking=no -i $CI_SSH_KEY ./api/api-app $DEPLOY_USER@$HOST:$DEPLOY_PATH
    - scp -o StrictHostKeyChecking=no -i $CI_SSH_KEY ./api/.env.production $DEPLOY_USER@$HOST:$DEPLOY_PATH/api-app/.env
    - ssh -o StrictHostKeyChecking=no -i $CI_SSH_KEY $DEPLOY_USER@$HOST "
      cd $DEPLOY_PATH && pm2 start ecosystem.config.js"
