image: node:23-alpine

stages:
  - setup
  - deploy

variables:
  DEPLOY_PATH: '/var/www/'
  DEPLOY_USER: 'gitlabci'
  HOST: '192.168.75.18'

before_script:
  - apk add --no-cache openssh
  - chmod 400 $CI_SSH_KEY

deploy_and_run_api:
  stage: deploy
  only:
    - main
  script:
    - echo "Installing dependencies and building the API..."
    - cd ./api
    - npm install
    - node ace build
    - scp -r -o StrictHostKeyChecking=no -i $CI_SSH_KEY ./api-app $DEPLOY_USER@$HOST:$DEPLOY_PATH
    - ssh -o StrictHostKeyChecking=no -i $CI_SSH_KEY $DEPLOY_USER@$HOST "
      cd /var/www/api-app &&
      npm ci --omit="dev" &&
      cp /etc/secrets/.env . &&
      pm2 delete ecosystem.config.js || true &&
      pm2 start ecosystem.config.js"
