image: node:18-alpine

stages:
  - deploy

variables:
  API_DEPLOY_PATH: '/var/www/api'
  FRONTEND_DEPLOY_PATH: '/var/www/frontend'
  DEPLOY_USER: 'gitlabci'
  API_HOST: '192.168.75.18'
  FRONT_HOST: '192.168.75.18'

# Deploy Express / Adonis API
deploy_and_run_api:
  stage: deploy
  only:
    - main
  script:
    - scp -r -o StrictHostKeyChecking=no -i $CI_SSH_KEY ./api/* $DEPLOY_USER@$API_HOST:$API_DEPLOY_PATH
    - ssh -o StrictHostKeyChecking=no -i $CI_SSH_KEY $DEPLOY_USER@$API_HOST "
        cd $API_DEPLOY_PATH &&
        npm install &&
        pm2 delete api || true &&
        pm2 start server.js --name api"

# Deploy Vue App
deploy_vue_app:
  stage: deploy
  only:
    - main
  script:
    - scp -r -o StrictHostKeyChecking=no -i $CI_SSH_KEY ./frontend/* $DEPLOY_USER@$FRONT_HOST:$FRONTEND_DEPLOY_PATH
    - ssh -o StrictHostKeyChecking=no -i $CI_SSH_KEY $DEPLOY_USER@$FRONT_HOST "
        cd $FRONTEND_DEPLOY_PATH &&
        npm install &&
        npm run build &&
        pm2 delete frontend || true &&
        pm2 serve dist 3000 --name frontend"
